ALTER TABLE recipes
DROP COLUMN cook_time_in_minute,
DROP COLUMN prep_time_in_minute,
DROP COLUMN description,
DROP COLUMN image_url,
DROP COLUMN recipe_yield,
DROP COLUMN category,
DROP COLUMN cuisine,
DROP COLUMN imported_from;
