on: [push]

name: Continuous integration

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: nightly-2020-06-23
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: check

    test:
        name: Test Suite
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: test_user
                    POSTGRES_PASSWORD: test_password
                    POSTGRES_DB: test_db
                    POSTGRES_PORT: 5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: nightly-2020-06-23
                  override: true
            - uses: actions-rs/install@v0.1
              with:
                  crate: diesel_cli
                  version: latest

            - name: run migration
              run: diesel migration run
              env:
                  DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db

            - uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: -- --test-threads=1
              env:
                  TEST_DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
                  DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db

    fmt:
        name: Rustfmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: nightly-2020-06-23
                  override: true
            - name: Rust version check
              uses: actions-rs/cargo@v1
              with:
                  command: version
            - run: rustup component add rustfmt
            - uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --all -- --check

    clippy:
        name: Clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: nightly-2020-06-23
                  override: true
            - run: rustup component add clippy
            - uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: -- -D warnings
